### ISSUE TITLE
@browser.navigateTo() should set headers for all requests the browser makes.

### ISSUE THREAD

**Issue by swerner** [groupon-testium/testium#120]
When you set headers in the @browser.navigateTo() function, the headers should be set globally (or there should be an option to pass them along for all other requests the browser performs) so any ajax calls that are made during the test should have those headers as well.

**Comment by EndangeredMassa** [comment]
I don't think there's a great way to add support for this. I suggest finding a different way to test your use case. Let me know if anyone thinks we can add this support.
