### ISSUE TITLE
Feedback about document

### ISSUE THREAD

**Issue by azu** [groupon-testium/testium#122]
Hi! Thanks for nice tools :sparkles: 
I started to use testium, then  I had a couple suggestion.

(My English is not good but hope you understand me...)

### 1. minimum setup

To work testium took a little longer than I anticipated.
I suggest that prepare officially minimum setup example. (something like [jkrems/testium2-demo](https://github.com/jkrems/testium2-demo "jkrems/testium2-demo"))

I'v created [azu/testium-seed](https://github.com/azu/testium-seed "azu/testium-seed") which is a example of minimum setup.

I have wanted to get a example which is actually work.

### 2. copy/pastable configuration

The [Configuration](https://github.com/groupon-testium/testium#configuration "Configuration") not seem to be copy/pastable.

At first, I pasted the [Configuration](https://github.com/groupon-testium/testium#configuration "Configuration") to `.testiumrc` and it didn't work.

I was confused.
![2015-01-20_15-32-02](https://cloud.githubusercontent.com/assets/19714/5813029/812bf388-a0b9-11e4-9fb1-720c86751478.jpg)
(and error message not have much meaning for me...)

I suggest that [Configuration](https://github.com/groupon-testium/testium#configuration "Configuration") is better to be copy/pasta**ble**.

Related PR: #123 

### 3. Don't Ignore Errors

The `.testiumrc` should be error, but only ignore error.

```
; .testiumrc
launch : true
```

The `.testiumrc` should be parse error and output error like follwonig:

```
launch : true
        ^ Error: Line 2: Unexpected token :
```

### 4. Missing wiki?

> For help debugging your tests, check out  [the wiki page](https://github.com/groupon/testium/wiki/Debugging-Your-Tests).
> -- README.md

https://github.com/groupon/testium/wiki/Debugging-Your-Tests is 301.

----

Maybe these are not actual issue.

Thanks.

**Comment by EndangeredMassa** [comment]
Thanks for the reports!

Items 2 and 4 have been fixed. Items 1 and 3 are definitely worth doing.

In the future, please submit a new issue for each item. That will make it easier to track each individual thing.

**Comment by azu** [comment]
@EndangeredMassa Thanks!

> In the future, please submit a new issue for each item. That will make it easier to track each individual thing.

Sorry, I'll be careful

**Comment by EndangeredMassa** [comment]
* moved item 1 to https://github.com/groupon-testium/testium/issues/126
* moved item 3 to https://github.com/groupon-testium/testium/issues/127
