### ISSUE TITLE
show error messages when .testiumrc is invalid

### ISSUE THREAD

**Issue by EndangeredMassa** [groupon-testium/testium#127]
An invalid `.testiumrc` doesn't show errors.

```
; .testiumrc
launch : true
```

This should show an error like the following:

```
launch : true
        ^ Error: Line 2: Unexpected token :
```

**Comment by jkrems** [comment]
This might be a bug worth reporting to rc (unless we are misusing that module in some way) - https://github.com/dominictarr/rc/issues.

**Comment by EndangeredMassa** [comment]
Yeah, this looks like something that could be addressed in [rc](https://github.com/dominictarr/rc/issues), but I'm not sure what the best way is to do that. Feel free to open an issue there.
