### ISSUE TITLE
Improve onboarding when using --download-selenium

### ISSUE THREAD

**Issue by searls** [groupon-testium/testium#133]
Today @timwingfield and I had a rocky onboarding experience with an existing project using Testium. It worked fine when we ran the test suite with phantomjs, but when running with `--browser chrome` we got an ENOENT error  stat'ing node_modules/testium/node_modules/bin/chromedriver.

We didn't know how to proceed so we tried these and they didn't help:

```
$ npm i -g testium 
$ testium --download-selenium #<-- the README suggested this might work
```

Then we got the same error. It was only once @endangeredmassa mentioned we should run locally (e.g. `./node_modules/.bin/testium --download-selenium`) that we got to our next error (which was that Java wasn't installed).

Thoughts on improving the onboarding? I feel like it would have been helpful if the README told us to run with the local bin, or if the global actually installed locally. Additionally when the bin is missing (but expected), a clearer error message would have been helpful.

**Comment by EndangeredMassa** [comment]
README issues addressed here: https://github.com/groupon-testium/testium/pull/134

What version of testium was this? ENOENT issues should have been fixed in [2.5.0](https://github.com/groupon-testium/testium/releases/tag/v2.5.0) here: https://github.com/groupon-testium/testium/pull/128

**Comment by EndangeredMassa** [comment]
Global support discussed here: https://github.com/groupon-testium/testium/issues/136

**Comment by EndangeredMassa** [comment]
When I try this locally without java and without a local chromedriver, I get:

```
See the full log at: /home/smassa/source/testium/test/integration_log/selenium.log
Error: Unable to find java
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

@searls what exactly did you see when trying this locally? How can I reproduce it?

**Comment by searls** [comment]
I am running 2.5.0

When `node_modules/testium/bin/chromedriver` does not exist (e.g. I haven't run `--download-selenium` yet), I get:

```
> testium --browser chrome

Preparing chrome...

/Users/justin/code/testdouble/my-project/node_modules/testium/lib/cli/console.js:112
      throw error;
            ^
Error: ENOENT, stat '/Users/justin/code/testdouble/my-project/node_modules/testium/bin/chromedriver'

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "test-console"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.5
npm ERR! code ELIFECYCLE
npm ERR! my-project@0.0.0 test-console: `testium --browser chrome`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the my-project@0.0.0 test-console script.
npm ERR! This is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     testium --browser chrome
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justin/code/testdouble/my-project/npm-debug.log
```

**Comment by searls** [comment]
You should be able to reproduce by just running `rm node_modules/testium/bin/chromedriver` and then running `testium --browser chrome`

**Comment by EndangeredMassa** [comment]
When I try removing chromedriver and java, I don't see that error.

Are you running that with a local testium? The example makes it appear to be global.

**Comment by searls** [comment]
That was executed with `npm run test-console` which is configured in package.json as:

```
    "test-console": "./node_modules/.bin/testium --browser chrome"
```

**Comment by EndangeredMassa** [comment]
Ah, I managed to reproduce this. Will fix.

**Comment by EndangeredMassa** [comment]
Fix for running without a local chromdriver: https://github.com/groupon-testium/testium/pull/137

**Comment by EndangeredMassa** [comment]
Closing this issue in favor of linked issues/PRs.
