### ISSUE TITLE
testium doesn't work as a global install

### ISSUE THREAD

**Issue by EndangeredMassa** [groupon-testium/testium#136]
```shell
$ npm install -g testium
...
$ testium 
Preparing phantomjs...

/home/smassa/.nvm/v0.10.36/lib/node_modules/testium/lib/cli/console.js:112
      throw error;
            ^
Error: ENOTDIR, mkdir '/usr/bin/test/log'
```

Should we make sure it works globally? If not, we should at least throw an error and document that it only works locally.

**Comment by searls** [comment]
My preference is for globally installed modules that expose a CLI is to behave like this:

1. First, attempt to resolve a local install from the current working directory (One approach [here](https://github.com/cabbagejs/cabbage-cli/blob/master/lib/cli.coffee#L15-L32))
2. If not locally installed, make available the CLI commands that make sense globally (for example, in Lineman if there's a global install but no local install, it'll just take over and do everything lineman would do as if it were locally installed to save space for folks who have a bunch of projects or know they want to run latest)

**Comment by EndangeredMassa** [comment]
I don't think this needs to be a global. It's yet another thing to maintain and I don't think it offers much value.
