### ISSUE TITLE
Right way to use debugger to debug test failures

### ISSUE THREAD

**Issue by toolbear** [groupon-testium/testium#141]
Problem: getting a 404, expecting a 200. Want to use node-inspector to debug the app that tests are running against.

What's the right way to go about this? Current hypothesis (update: it worked, steps revised to reflect what we did):

1. run `node-inspector` and connect to debugger in Chrome/whatever using the URL echoed by `node-inspector`
2. set `launch = false` in `.testiumrc`
3. Specify constant port number via `app.port` in `.testiumrc` OR `export PORT=something`
4. add `debugger` statement in production code
5. run your app with `node --debug-brk app.js`
6. run tests as normal (not under debugger)

Gotchas: don't simultaneously run your app under the debugger and your unit tests under the debugger. Bad things will happen.

About to try this out, but would appreciate any other advice on how to debug our app under test. :beers:

**Comment by jkrems** [comment]
Hi! Sorry for the late reply. I'm assuming 4. and 5. should be switched around but otherwise that sounds like the way to go. You also might want to fix down the app port in `.testiumrc` in case you didn't already. Would be great to hear how it went/if there were any problems!

**Comment by toolbear** [comment]
Got it working. Updated description above with the steps that worked for us. Closing.

**Comment by johan** [comment]
:+1: on sharing your discoveries, the [XKCD](http://xkcd.com/979/) approved way! :-D

![what did you see](http://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
