### ISSUE TITLE
Deprecate img-diff functionality

### ISSUE THREAD

**Issue by EndangeredMassa** [groupon-testium/testium#149]
The img-diff functionality is nice, but it's basic and slow. I don't know of many people using it. It could be made better, but it would require concentrated effort in that area. In the mean time, it's causing some [io.js compatibility issues](https://github.com/groupon-testium/testium/pull/148). It's also confusing when the optional `img-diff` dependency fails to install because `libpng` isn't installed.

I think we should deprecate all methods that require [img-diff](https://github.com/groupon-testium/testium/blob/master/src/img_diff.coffee).

**Comment by jkrems** [comment]
:+1:
