### ISSUE TITLE
Unable to switch nested frames

### ISSUE THREAD

**Issue by kawausokun** [groupon-testium/testium#153]
```html
<frameset>
  <frame name="top">
  <frameset>
    <frame name="left">
    <frame name="right">
  </frameset>
</frameset>
```
Is there a way I can access left frame?

**Comment by EndangeredMassa** [comment]
It looks like you'll have to switch to the `top` frame, then to the `left` frame. Something like this:

```coffee
@browser.switchToFrame('top')
@browser.switchToFrame('left')
```

I added a test for this. https://github.com/groupon-testium/testium/commit/2b00fa97b1c20623f642eb8871440a27fd5ff38e
