### ISSUE TITLE
Chrome Warning: “You are using an unsupported command-line flag –ignore-certificate-errors. Stability and security will suffer.”

### ISSUE THREAD

**Issue by EndangeredMassa** [groupon-testium/testium#77]
Testium uses chromedriver to connect to Chrome, which starts Chrome with the flag `–ignore-certificate-errors` by default. A somewhat recent version of Chrome added this flag to the list of "bad flags", which causes a warning banner to show up when you start the browser.

Supposedly, you can fix this by either adding "--test-type" to the args or by adding `excludeSwitches="ignore-certificate-errors"` to the [chromeOptions capabilities object](https://sites.google.com/a/chromium.org/chromedriver/capabilities). Neither fixes the problem for me, but many report that both will work.

We need to find a way to make this banner not show up.

**Comment by sholladay** [comment]
@EndangeredMassa did you ever find a way to fix this?

**Comment by EndangeredMassa** [comment]
I should have added a comment. I don't see this anymore. Do you?
